POST https://node-do-zero-f272.onrender.com/videos
Content-Type: application/json


{
  "title" : "Video node",
  "description" : "Video 01 é esse",
  "duration": 200

}

###

GET https://node-do-zero-f272.onrender.com/videos


###
GET https://node-do-zero-f272.onrender.com/videos?search=testeeeeeeeeeee


###
PUT https://node-do-zero-f272.onrender.com/videos/ff73b331-c747-430c-bbba-d5c203add6b6
Content-Type: application/json


{
  "title" : "Video testeeeeeeeeeee",
  "description" : "Video 01 é esse",
  "duration": 200

}

###
DELETE  https://node-do-zero-f272.onrender.com/videos/ff73b331-c747-430c-bbba-d5c203add6b6
