POST http://localhost:3333/videos
Content-Type: application/json


{
  "title" : "Video 01",
  "description" : "Video 01 é esse",
  "duration": 200

}

###

GET http://localhost:3333/videos


###
GET http://localhost:3333/videos?search=node


###
PUT http://localhost:3333/videos/ab2ed553-490c-4bd8-9635-a7d82a3ca014
Content-Type: application/json


{
  "title" : "Video 01111",
  "description" : "Video 01 é esse",
  "duration": 200

}

###
DELETE  http://localhost:3333/videos/8a74468b-6501-4a3a-9e2a-4b638f7e0552
