POST http://localhost:3334/videos
Content-Type: application/json


{
  "title" : "Video node",
  "description" : "Video 01 é esse",
  "duration": 200

}

###

GET http://localhost:3334/videos


###
GET http://localhost:3334/videos?search=testeeeeeeeeeee


###
PUT http://localhost:3334/videos/ff73b331-c747-430c-bbba-d5c203add6b6
Content-Type: application/json


{
  "title" : "Video testeeeeeeeeeee",
  "description" : "Video 01 é esse",
  "duration": 200

}

###
DELETE  http://localhost:3334/videos/ff73b331-c747-430c-bbba-d5c203add6b6
